create table users
(
    id      bigint generated by default as identity
        constraint user_pk
            primary key,
    name    varchar not null,
    surname varchar not null,
    mail    varchar
);